name: Simple Workflow

on:
    workflow_dispatch:
     inputs:
      environment:
        description: 'Provide some input'     
        required: false
        default: 'type smth'
jobs:

    printInputs:
        runs-on: ubuntu-latest
        steps:
        - run: |
                echo "Env: ${{ github.event.inputs.environment }}" 
                echo "Branch: ${{ github.event.inputs.branch }}"

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.md
              path: /home/runner/work/devops-school/devops-school/log.md
